sonar.projectKey=outsource_charlie-M_93699a0f-904c-4cb9-a556-c24168e6eb0e
sonar.qualitygate.wait=true
sonar.pullrequest.key=.CI_MERGE_REQUEST_IID
sonar.pullrequest.base=.CI_MERGE_REQUEST_TARGET_BRANCH_NAME
sonar.pullrequest.branch=.CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
sonar.projectBaseDir=.
sonar.cpd.cross_project=false